name: RankPlugin
version: '1.0-SNAPSHOT'
main: Akmiru.rankPlugin.RankPlugin
api-version: '1.21'
commands:
  apermission:
    description: Assings a rank to a player
    usage: /apermission <player> <rank>
    permission: rankplugin.setrank
  permissions:
    rankplugin.setrank:
      description: Allows setting a player's rank
      default: op
dependencies:
  bootstrap:
